# -*- coding: utf-8 -*-
"""LinearRegressionSklearn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvmOX0Cty4AsLXuupSeAgPqbQ4flsAZf
"""

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


data = fetch_california_housing()
X = data.data
y = data.target


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)

print("Test Mean Squared Error:", mse)
print("Intercept:", model.intercept_)
print("Coefficients:")
for name, coef in zip(data.feature_names, model.coef_):
    print(f"{name}: {coef}")





