# -*- coding: utf-8 -*-
"""LinearRegressionScratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jr4g2Uod3sgDI_LzNnQzIJLNuUZRCJZ9
"""

import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


data = fetch_california_housing()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


# Closed Form
X_train_bias = np.c_[np.ones(X_train.shape[0]), X_train]
beta = np.linalg.inv(X_train_bias.T @ X_train_bias) @ X_train_bias.T @ y_train
intercept = beta[0]
coefficients = beta[1:]
X_test_bias = np.c_[np.ones(X_test.shape[0]), X_test]
y_pred = X_test_bias @ beta


mse = mean_squared_error(y_test, y_pred)
print("Test Mean Squared Error:", mse)
print("Intercept:", intercept)
print("Coefficients:")
for name, coef in zip(data.feature_names, coefficients):
    print(f"{name}: {coef}")

