# -*- coding: utf-8 -*-
"""MultipleLinearRegressionSGD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YBImfXZeXURpiGv7Vj6g19iBGBMCnlt
"""

import random
import numpy as np
import matplotlib.pyplot as plt

X = np.random.rand(100, 10)
Y = np.sum(X * np.random.rand(100, 10), 1) + np.random.rand(100)

def get_f(w, b):
  def f(x):
    return np.sum(w * x) + b
  return f

def SSE(f, X, Y):
  return np.sum(np.square(Y - f(X)))

def dSSE(f, X, Y):
  delta = f(X) - Y
  db = 2 * np.sum(delta)
  dm = 2 * np.sum(X * delta[:, np.newaxis])
  return db, dm

alpha = 0.000001
max_iter = 10
b = random.random()
m = np.random.rand(10)
for _ in range(max_iter):
  f = get_f(m, b)
  db, dm = dSSE(f, X, Y)
  b -= alpha * db
  m -= alpha * dm
  print(f"{_}) ", f"loss = {SSE(f, X, Y)}", f"{b = }", f"{m = }", sep="\n", end="\n\n")

