# -*- coding: utf-8 -*-
"""UnivariateLinearRegressionSGD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AtjM48om5qUuX4pUcrRPy3KEy6vccVui
"""

import random
import numpy as np
import matplotlib.pyplot as plt

X = np.random.randn(100)
Y = X * np.random.ranf(100) + np.random.ranf(100)

plt.scatter(X, Y)

def get_f(w, b):
  def f(x):
    return w * x + b
  return f

def SSE(f, X, Y):
  return np.sum(np.square(Y - f(X)))

def dSSE(f, X, Y):
  delta = f(X) - Y
  db = 2 * np.sum(delta)
  dm = 2 * np.sum(delta * X)
  return db, dm

alpha = 0.001
max_iter = 100
m = random.random()
b = random.random()
for _ in range(max_iter):
  f = get_f(m, b)
  db, dm = dSSE(f, X, Y)
  b -= alpha * db
  m -= alpha * dm
  print(f"{_}) ", f"loss = {SSE(f, X, Y)}", f"{b = }", f"{m = }", sep="\n", end="\n\n")

Y_hat = m * X + b

plt.scatter(X, Y)
plt.plot(X, Y_hat, color="red")
plt.show()

