# -*- coding: utf-8 -*-
"""UnivariateLinearRegressionOLS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqlgD19E1oYMH0pds4JyHpOD4aNWny0R
"""

import numpy as np
import matplotlib.pyplot as plt

X = np.random.randn(100)
Y = X * np.random.ranf(100) + np.random.ranf(100)

plt.scatter(X, Y)
plt.show()

x_avg = np.mean(X)
y_avg = np.mean(Y)

m_nom = np.sum((X - x_avg) * (Y - y_avg))
m_denom = np.sum((X - x_avg) ** 2)

m = m_nom / m_denom
b = y_avg - m * x_avg

print(f"{m = }")
print(f"{b = }")

Y_hat = m * X + b

plt.scatter(X, Y)
plt.plot(X, Y_hat, color="red")
plt.show()

sse = np.sum((Y - Y_hat) ** 2)
mse = np.mean((Y - Y_hat) ** 2)
sae = np.sum(np.abs(Y - Y_hat))
mae = np.mean(np.abs(Y - Y_hat))

print(f"{sse = }")
print(f"{mse = }")

print(f"{sae = }")
print(f"{mae = }")

